config/routes.rb
Rails.application.routes.draw do
  #User authentication
  root 'images#index'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  #images
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :attachment, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates :title, :presence => true
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/
  belongs_to :user
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :images
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  has_many :images


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
    @image_owner = User.find(@image.user_id)
    @current_user = current_user
  end

  def new
    @user = current_user
    @image = @user.images.new
  end

  def create
    @user = current_user
    @image = @user.images.new(image_params)
    if @image.save
      redirect_to images_path,  notice: "image successfully added!"
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
    @user = current_user
    @users = User.all
  end

  def update
    @image = Image.find(params[:id])
    @user = current_user
    @tags = @image.tags
    if @image.update(image_params)
      @tags.push()
      redirect_to image_path(@image), notice: "Image successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])

    @image.destroy
    redirect_to images_path
  end

  private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def image_params
    params.require(:image).permit(:attachment, :title, :user_id)
  end

  def get_all_tags
    @tags = User.all
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
     flash[:notice] = "You've successfully signed up!"
     session[:user_id] = @user.id
     redirect_to "/"
   else
     flash[:alert] = "There was a problem signing up."
     redirect_to '/signup'
   end
 end

 private

 def user_params
   params.require(:user).permit(:email, :name, :password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/images/_form.html.erb
<%= render('layouts/errors', :object => @image) %>

<%= simple_form_for [@user, @image], url: images_path do |form| %>
  <%= form.input :title, as: :string %>
  <%= form.input :attachment, as: :file %>
  <%= form.submit class: 'btn btn-success'%>
<% end %>

app/views/images/edit.html.erb
<h1>Edit Image</h1>
<%=image_tag @image.attachment.url(:medium) %>
<%= render('layouts/errors', :object => @image) %>

<%= simple_form_for [@user, @image], url: image_path do |form| %>
  <%= form.input :title, as: :string %>
  <%=  %>
  <%= form.input :attachment, as: :file %>
  <%= form.collection_check_boxes :tag_ids, @tags, :id, :name do |t| %>
    <%= t.label do %>
      <%= t.check_box + t.text %>
    <% end %>
  <%end  %>
  <%= form.submit class: 'btn btn-success'%>
<% end %>

app/views/images/index.html.erb
<h1>Images#index</h1>
<ul>
  <% @images.each do |image|  %>
    <li>
      <%= image.title  %>
    </li>
    <li>
      <%= link_to image do %>
        <%=image_tag image.attachment.url(:medium) %>
      <% end %>  
    </li>
  <% end %>
</ul>

app/views/images/new.html.erb
<%= simple_form_for [@user, @image], url: images_path do |form| %>
  <%= form.input :attachment, as: :file %>
  <%= form.input :title, as: :string %>
  <%= form.submit class: 'btn btn-success'%>
<% end %>

app/views/images/show.html.erb
<h1>Images#show</h1>

<%=image_tag @image.attachment.url(:medium) %>
<h6><%= @image.title  %> by <%= @image_owner.name %></h6>


<% if @current_user == @image_owner %>
<%= link_to 'Edit Image', edit_image_path, :class => 'btn btn-success'  %>
  <%= link_to 'Delete Image', image_path(@image, @image_owner), :method =>'delete', :data => {:confirm => 'You sure?'}, :class => 'btn btn-danger'%>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Dashboard</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/images/new">Add Image</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
        <span class="navbar-brand">
          <% if current_user %>
            <%= current_user.name %> | <%= link_to "Sign out", '/signout', class: 'user-button' %>
          <% else %>
            <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin', class: 'user-button' %>
          <% end %>
        </span>
      </div>
    </nav>
    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Flick Clone</h1>
        <p class="lead text-muted">Share Your Image Today</p>
        <p>
          <a href="#" class="btn btn-primary">Sign Up</a>
          <a href="#" class="btn btn-secondary">Sign In</a>
        </p>
      </div>
    </section>
    <div class="container">

      <% if current_user %>
        <%= current_user.name %> | <%= link_to "Sign out", '/signout' %>
      <% else %>
        <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
      <% end %>

      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>